
# Nombre del servicio
spring.application.name=products-service

# Base de datos H2 (in-memory para prototipo)
spring.datasource.url=jdbc:h2:mem:productsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (solo para desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=${SERVER_PORT:8080}

# Datos iniciales
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.info.title=Products Service API
springdoc.info.description=Microservicio de gestion de productos para ShopSmart
springdoc.info.version=1.0.0
